version: 2
jobs:
  build:
    docker:
      - image: namachan10777/folivora:latest

    steps:
      - checkout
      - run:
          name: Pull submodules
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: 3d parts build
          command: |
            eval $(opam config env)
            mkdir -p ~/.local/share
            make archive -C 3d
      - run:
          name: Zip pcb files
          command: ./zip-pcb-files.sh
      - store_artifacts:
          path: ./3d/3d.tar.zstd
          destination: 3d.tar.zstd
      - store_artifacts:
          path: ./pcb.zip
          destination: pcb.zip
