version: 2
jobs:
  build:
    docker:
      - image: namachan10777/folivora:latest

    steps:
      - checkout
      - run:
          name: Pull submodules
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: 3d parts build
          command: |
            mkdir -p ~/.local/share
            ./3d/build.sh
      - run:
          name: Zip pcb files
          command: ./zip-pcb-files.sh
      - store_artifacts:
          path: ./3d/3d.zip
          destination: 3d
      - store_artifacts:
          path: ./pcb.zip
          destination: pcb
