version: 2
jobs:
  build:
    docker:
      - image: namachan10777/folivora:latest

    steps:
      - checkout
      - run:
          name: Pull submodules
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: 3d parts build
          command: ./3d/build.sh
