version: 2
jobs:
  build:
    docker:
      - image: namachan10777/folivora:latest

    steps:
      - checkout
      - run:
          name: 3d parts build
          command: |
            eval $(opam config env)
            make archive -C model
      - store_artifacts:
          path: ./model/archive.tar.zst
          destination: archive.tar.zst
